### PR TITLE
drivers/snowflake: Add RowsAffected to fix DDLs

### PR DESCRIPTION
**Pull request by Preston4tw**
This is a follow up from #114 to also commit the patch from the comments.

### CODE REVIEW

**Comment by kenshaw** [comment]
I've already added a general case to `usql` to recognize Go's `driver.ResultNoRows` value in commit #5c7fb6f7b82a855cb6b0e3413c180f9827122e88. Is there a reason you want to add this? Try with 5c7fb6f7b82a855cb6b0e3413c180f9827122e88 and let me know if there are other errors being kicked back to `usql` on DDL statements.

**Comment by Preston4tw** [comment]
I may be misunderstanding the 5c7fb6f commit. Without this PR usql >= 5c7fb6f still throws errors on DDLs:

```
C02XJ5KKJGH5:usql pbennes$ git log -n1 --pretty='%h'
a0a0cc7
C02XJ5KKJGH5:usql pbennes$ git status
HEAD detached at a0a0cc7
nothing to commit, working tree clean
C02XJ5KKJGH5:usql pbennes$ go build -tags snowflake
C02XJ5KKJGH5:usql pbennes$ ./usql 'snowflake://preston4tw@test/'
Connected with driver snowflake (<unknown>)
Type "help" for help.

sf:admin@test=> create database preston4tw;
error: snowflake: no RowsAffected available after DDL statement
sf:admin@test=> drop database preston4tw;
error: snowflake: no RowsAffected available after DDL statement
```

**Comment by kenshaw** [comment]
Ok. Let me check and see what's going on. I am probably not using Go's `sql` + `driver` APIs correctly.

**Comment by kenshaw** [comment]
I've fixed the logic. I had assumed that value was being returned directly, but it is not. Kind of an odd implementation decision, but whatever. Please update to the latest code and let me know if that is working properly for you.

**Comment by Preston4tw** [comment]
That did it. TYVM @kenshaw !

**Pull request closed without merging**
